version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2017
environment:
  NUGET_API_KEY:
    secure: Gh710okfD06O3QGAaOWY1gvL/FjnBLUgJHsMxY0qrud2CiF3V+sYFNdYDAXak8YR
build_script:
- cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "AppVeyor"
test: off
